# Site settings
title: BMI-projekti
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  BMI-projekti tuo yhteen...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
exclude: ["leiska"]
# Build settings
markdown: kramdown
